default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: 127.0.0.1
  port: 5432
  password: password

development:
  <<: *default
  database: ecostay_apartment_db

test:
  <<: *default
  database: ecostay_apartment_test

production:
  <<: *default
  database: ecostay_apartment_production
  username: ecostay_apartment
  password: <%= ENV['ECOSTAY_APARTMENT_DATABASE_PASSWORD'] %>
