default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: 127.0.0.1
  port: 5432
  password: password

development:
  <<: *default
  database: ecostay_apartment_db

test:
  <<: *default
  database: ecostay_apartment_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: ecostay_apartment_production
  username: root
  host: dpg-cehtujsgqg4e0ef8jr5g-a.singapore-postgres.render.com
  port: 5432
  password: uDqKjsikEyMM9q3LBAAME2V9QfbLOhfI
